# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVerify():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_verify(self):
    self.driver.get("http://automationpractice.com/index.php")
    assert self.driver.title == "My Store"
    self.driver.find_element(By.LINK_TEXT, "Sign in").click()
    assert self.driver.title == "Login - My Store"
    self.driver.find_element(By.CSS_SELECTOR, "#SubmitLogin > span").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "ol > li").text == "An email address required."
  
