# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPracticeForm():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_practiceForm(self):
    self.driver.get("http://www.practiceselenium.com/practice-form.html")
    self.driver.find_element(By.NAME, "firstname").send_keys("Huong")
    self.driver.find_element(By.NAME, "lastname").send_keys("Nguyen Thi")
    self.driver.find_element(By.ID, "sex-1").click()
    self.driver.find_element(By.ID, "exp-6").click()
    self.driver.find_element(By.ID, "tea1").click()
    self.driver.find_element(By.ID, "tea2").click()
    self.driver.find_element(By.ID, "tool-0").click()
    self.driver.find_element(By.ID, "tool-1").click()
    dropdown = self.driver.find_element(By.ID, "continents")
    dropdown.find_element(By.XPATH, "//option[. = 'Asia']").click()
    dropdown = self.driver.find_element(By.ID, "selenium_commands")
    dropdown.find_element(By.XPATH, "//option[. = 'Browser Commands']").click()
    self.driver.find_element(By.ID, "submit").click()
  
